users:
  admin:
    email: wwwkhalfi@gmail.com
    password: $2b$12$xchoVFQUrTiWsVa4sCNBBOUuz7y0F3HOP/G4L96TFwECqdnFUhq.a
  samikh:
    email: wwwkhalfi2003@gmail.com
    password: $2b$12$4iNEJidBAtb85XV8L81W8.ebsXiJHwRzF0JFtNn4T9odp8.o/b7dW
